#%RAML 1.0
---

title: Breathing Space
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/xml

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

documentation:
  - title: Overview
    content: !include docs/overview.md

/individuals/breathing-space:
#  /debtor:
#    /{nino}:
#      /details:
#        uriParameters:
#          nino:
#            description: |
#              National Insurace Number
#
#              Must be a valid NINO string.
#            type: string
#            example: "QQ123456C"
#        get:
#          displayName: Get the details of an individual by their NINO
#          description: Get the details of an individual by their given NINO.
#          (annotations.scope): "read:breathing-space-debtor"
#          securedBy: [ sec.oauth_2_0: { scopes: [ "read:breathing-space-debtor" ] } ]
#          headers:
#            Content-Type:
#              description: Specifies the content type of the request payload. Must be same as the example given.
#              type: string
#              required: true
#              example: application/json
#            Correlation-Id:
#              description: A unique UUID for this request
#              type: string
#              required: true
#              example: 24a8a24f-7126-4aa7-b690-259b2eaccaee
#            Request-Type:
#              description: |
#                Context flag for this request. Signifies if this request is the result of a human attended operation or an automated operation.
#
#                The two possible values are ‘DA2_BS_ATTENDED’ or ‘DA2_BS_UNATTENDED’.
#              type: string
#              required: true
#              example: DA2_BS_ATTENDED
#            Staff-Id:
#              description: |
#                The Staff identifier associated with the human attending the operation that generated this request.
#
#                Must be a 7 digit numeric value
#              type: string
#              required: true
#              example: "1234567"
#          responses:
#            200:
#              body:
#                application/json:
#                  example: |
#                      {}
#            400:
#              body:
#                application/json:
#                  description: Invalid Request
#                  example: |
#                      <?xml version="1.0" encoding="UTF-8"?>
#                      <errorResponse>
#                          <code>BAD_REQUEST</code>
#                          <message>Payload is not valid according to schema</message>
#                          <errors>
#                              <error>
#                                  <code>xml_validation_error</code>
#                                  <message>Error at line 13, column 13: no declaration found for element 'unknown'</message>
#                              </error>
#                          </errors>
#                      </errorResponse>
#            500:
#              body:
#                application/json:
#                  description: Internal server error
#                  example: |
#                      <?xml version="1.0" encoding="UTF-8"?>
#                      <errorResponse>
#                          <code>INTERNAL_SERVER_ERROR</code>
#                          <message>Internal server error</message>
#                      </errorResponse>
#
  /{nino}:
    uriParameters:
      nino:
        description: |
          National Insurance Number.

          Must conform to the regular expression

          <code>^((?:[ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-TW-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D ]?$</code>
        type: string
        example: "MZ006526C"
    /periods:
      get:
        displayName: Retrieve all Breathing Space periods for a NINO
        description: Retrieve all Breathing Space periods for the given NINO.
        (annotations.scope): "read:breathing-space-periods"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:breathing-space-periods" ] } ]
        headers:
          Content-Type:
            description: Specifies the content type of the request payload. Must be same as the example given.
            type: string
            required: true
            example: application/json
          Correlation-Id:
            description: A unique UUID for this request
            type: string
            required: true
            example: 24a8a24f-7126-4aa7-b690-259b2eaccaee
          Request-Type:
            description: |
              Context flag for this request. Signifies if this request is the result of a human attended operation or an automated operation.

              The two possible values are ‘DA2_BS_ATTENDED’ or ‘DA2_BS_UNATTENDED’.
            type: string
            required: true
            example: DA2_BS_ATTENDED
          Staff-Id:
            description: |
              The Staff identifier associated with the human attending the operation that generated this request.

              Please note the following additional validation rules apply to this header depending on the value of the 'Request-Type' header:
                - Request-Type == ‘DA2_BS_ATTENDED’ then this header value must NOT equal '0000000'
                - Request-Type == ‘DA2_BS_UNATTENDED’ then this header value must equal '0000000'

              Must be a 7 digit numeric value
            type: string
            required: true
            example: "1234567"
        responses:
          200:
            headers:
              Correlation-Id:
                description: A unique UUID for this request
                type: string
                required: true
                example: 24a8a24f-7126-4aa7-b690-259b2eaccaee
            body:
              application/json:
                type: !include schemas/CommonBsPeriodsResponse.json
                examples:
                  examples-1:
                    description: Multiple periods returned
                    value: !include examples/GetBsPeriodsResponse.json

          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  missingHeader:
                    description: One or more of the required headers are missing
                    value:
                      code: MISSING_HEADER
                  invalidHeader:
                    description: One or more of the header values are invalid
                    value:
                      code: INVALID_HEADER
                  invalidNino:
                    description: Invalid NINO format
                    value:
                      code: INVALID_NINO

          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  resourceNotFound:
                    description: The supplied NINO was not found
                    value:
                      code: RESOURCE_NOT_FOUND

          502:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  resourceNotFound:
                    description: Dependent systems are currently not responding
                    value:
                      code: BAD_GATEWAY

  /periods:
    post:
      displayName: Create new Breathing Space periods
      description: Create new Breathing Space periods for a given NINO.
      (annotations.scope): "write:breathing-space-periods"
      securedBy: [ sec.oauth_2_0: { scopes: [ "write:breathing-space-periods" ] } ]
      headers:
        Content-Type:
          description: Specifies the content type of the request payload. Must be same as the example given.
          type: string
          required: true
          example: application/json
        Correlation-Id:
          description: A unique UUID for this request
          type: string
          required: true
          example: 24a8a24f-7126-4aa7-b690-259b2eaccaee
        Request-Type:
          description: |
            Context flag for this request. Signifies if this request is the result of a human attended operation or an automated operation.

            The two possible values are ‘DA2_BS_ATTENDED’ or ‘DA2_BS_UNATTENDED’.
          type: string
          required: true
          example: DA2_BS_ATTENDED
        Staff-Id:
          description: |
            The Staff identifier associated with the human attending the operation that generated this request.

            Please note the following additional validation rules apply to this header depending on the value of the 'Request-Type' header:
             - Request-Type == ‘DA2_BS_ATTENDED’ then this header value must NOT equal '0000000'
             - Request-Type == ‘DA2_BS_UNATTENDED’ then this header value must equal '0000000'

            Must be a 7 digit numeric value
          type: string
          required: true
          example: "1234567"
      body:
        application/json:
          type: !include schemas/PostBsPeriodsRequest.json
          examples:
            examples-1:
              description: Create single period request
              value: !include examples/PostSingleBsPeriodsRequest.json
            examples-2:
              description: Create multiple periods request
              value: !include examples/PostMultipleBsPeriodsRequest.json
      responses:
        201:
          body:
            application/json:
              type: !include schemas/CommonBsPeriodsResponse.json
              examples:
                examples-1:
                  description: Single created periods returned
                  value: !include examples/PostSingleBsPeriodsResponse.json
                examples-2:
                  description: Multiple created periods returned
                  value: !include examples/PostMultipleBsPeriodsResponse.json

        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                missingHeader:
                  description: Missing Header
                  value:
                    code: MISSING_HEADER
                invalidHeader:
                  description: Invalid Header
                  value:
                    code: INVALID_HEADER
                missingBody:
                  description: Missing Body
                  value:
                    code: MISSING_BODY
                invalidJson:
                  description: Invalid Json
                  value:
                    code: INVALID_JSON
                invalidNino:
                  description: Missing Nino
                  value:
                    code: INVALID_NINO
                invalidDate:
                  description: Invalid Date
                  value:
                    code: INVALID_DATE
                invalidDateRange:
                  description: Invalid Date Range
                  value:
                    code: INVALID_DATE_RANGE

        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                resourceNotFound:
                  description: Resource specified by the supplied NINO was not found
                  value:
                    code: RESOURCE_NOT_FOUND
